# Generated by Django 2.2.2 on 2019-06-29 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190629_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookcase',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bookcase', to='webapp.Book', verbose_name='Книга на полке'),
        ),
        migrations.AlterField(
            model_name='bookcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookcase', to=settings.AUTH_USER_MODEL, verbose_name='Полка пользователь'),
        ),
    ]
